branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry
  - .alienbuild\plugin_fetch_cache

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  #  ensure we have some packages that aren't picked up by the install system
  #  or that need updating
  - cpanm --quiet --notest Alien::Build
  - cpanm --quiet --notest Alien::Build::MM
  - cpanm --quiet --notest Sort::Versions
  - cpanm --quiet --notest PkgConfig
  - cpanm --quiet Alien::Build::Plugin::Cleanse::BuildDir
  - cpanm --quiet --notest Alien::Build::Plugin::PkgConfig::PPWrapper
  #- cpanm -v Alien::curl | perl -ne "BEGIN {$|=1; open our $log, q|>|, q|build.log|};   print qq|\n| if 0 == ($. %% 100); print q|.|; print {$log} $_;" || type build.log;
  #- cpanm -v --notest https://github.com/shawnlaffan/perl-alien-proj.git
  #- cpanm --quiet --notest --installdeps .
  - cpanm --quiet --notest Alien::Build::Plugin::Fetch::Cache
  - cpanm -v Alien::sqlite
  - perl -MAlien::sqlite -E "say Alien::sqlite->version";
  - perl -MAlien::sqlite -E "say Alien::sqlite->install_type";
  - cpanm -v Alien::curl
  - cpanm -v Alien::libtiff

  - gcc -v

build_script:
  - set ALIEN_BUILD_PRELOAD=Fetch::Cache
  #- set ALIEN_PROJ_CONFIG_ARGS="--enable-tiff=no"
  - perl Makefile.PL
  - cpanm --installdeps --notest .

  - gmake
  - gmake test


